import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { StackProvider } from "@stackframe/stack";
import { stackServerApp } from "@/stack";
import { TooltipProvider } from "@/components/ui/tooltip";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const stackEnabled = !!process.env.NEXT_PUBLIC_STACK_PROJECT_ID;
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {stackEnabled ? (
          <StackProvider app={stackServerApp}>
            <TooltipProvider>
              {children}
              <SpeedInsights />
            </TooltipProvider>
          </StackProvider>
        ) : (
          <TooltipProvider>
            {children}
            <SpeedInsights />
          </TooltipProvider>
        )}
      </body>
    </html>
  );
}
